### ISSUE TITLE
Have cancel-backfill undo conflicting upmaps

### ISSUE THREAD

**Issue by CartCaved** [digitalocean/pgremapper#26]
I've been using pgremapper primarily for the purpose of being able to add more storage, new disks in existing hosts and/or new hosts, without causing a huge reshuffling. 

My problem is that when I run cancel-backfill, I get a panic - `conflicting mapping(s) found when trying to map from X to Y`. My purpose of running cancel-backfill is to just replace all the remappings in the crush map with remappings keeping all the data where it is, so that the balancer can gradually move everything to where it should be (the CERN way :))

As such, my workaround is to run `undo-upmaps Y --max-backfill-reservations 9999 --max-source-backfills 9999 --yes`, then rerun cancel-backfill, get a new panic and repeat the undo-upmaps manually for, sometimes, several hours.

I actually have `watch cancel-backfill --yes --concurrency 25` running in one window and a small script in another window letting me just type in the osd to undo-upmaps. With every undo-upmaps I get more and more misplaced pgs. When all the conflicting mappings have finally been found and undone, the `watch cancel-backfill` command will cancel everything and leave all the pgs where they are. Then I can run `ceph osd unset norebalance&&ceph osd unset nobackfill&&ceph balancer on` and watch how my cluster gently rebalances.

Maybe I'm just totally missing something, but what I would like is for pgremapper to automatically undo the conflicting upmaps when running cancel-backfill or at least take those into consideration when generating the new mappings. It would really cut down on the time I spend manually undoing upmaps!

**Comment by baergj** [comment]
Hey @CartCaved , we actually made that a non-fatal error in https://github.com/digitalocean/pgremapper/pull/24, so I think you just need to pull teh latest version and it should be better.

For context, historically we were concerned that by hiding this error we would miss cases that were important to handle. As the code comment explains in that PR, we've since found cases, particularly in EC pools, where "impossible" situations arise that we simply can't handle via upmaps. Thus, we now emit this as a warning in case someone wants to dig further.

As always, if you think pgremapper is making a wrong decision somewhere, please feel free to [collect the information listed in the README](https://github.com/digitalocean/pgremapper#bug-reports) and file a bug report and we can look into whether pgremapper can do better. Thanks!
